// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "auth": {
    "login": {
      "title": "Welcome back, Trainer!",
      "description": "Please enter your details to sign in",
      "emailLabel": "Email address",
      "emailPlaceholder": "Enter your email address",
      "passwordLabel": "Password",
      "passwordPlaceholder": "Enter your password",
      "submitButton": "Sign in",
      "submittingButton": "Signing in...",
      "errors": {
        "invalidEmail": "Please enter a valid email address.",
        "requiredPassword": "Password is required.",
        "api": {
          "accountNotFound": "No account found with this email.",
          "incorrectPassword": "Incorrect password."
        }
      }
    },
    "register": {
      "title": "Welcome to Pokemon Library!",
      "description": "Please enter your details to create an account",
      "nameLabel": "Name",
      "namePlaceholder": "Enter your name",
      "emailLabel": "Email address",
      "emailPlaceholder": "Enter your email address",
      "passwordLabel": "Password",
      "passwordPlaceholder": "Enter your password",
      "confirmPasswordLabel": "Confirm Password",
      "confirmPasswordPlaceholder": "Confirm your password",
      "submitButton": "Register",
      "submittingButton": "Registering...",
      "errors": {
        "requiredName": "Name is required.",
        "invalidEmail": "Please enter a valid email address.",
        "requiredPassword": "Password is required.",
        "requiredConfirmPassword": "Confirm password is required.",
        "passwordMismatch": "Passwords do not match.",
        "api": {
          "accountExists": "An account with this email already exists."
        }
      }
    }
  },
  "library": {
    "title": "Pokemon Library",
    "loading": "Loading Pokemon...",
    "listEnd": "All {pokemon} Pokemon loaded.",
    "error": {
      "fetchFailed": "Failed to load Pokemon. Please try again."
    }
  },
  "detail": {
    "height": "Height",
    "weight": "Weight",
    "baseExperience": "Base EXP",
    "baseStats": "Base Stats",
    "stats": {
      "hp": "HP",
      "attack": "Attack",
      "defense": "Defense",
      "special-attack": "Sp. Atk",
      "special-defense": "Sp. Def",
      "speed": "Speed"
    },
    "abilities": "Abilities",
    "hiddenLabel": " hidden",
    "back": "Back to the list"
  },
  "metadata": {
    "appName": "Pokemon Library",
    "description": "A simple app to browse and view details of Pokemon using the PokeAPI.",
    "descriptionPrefix": "Details about",
    "notFound": {
      "title": "Pokemon not found",
      "description": "The Pokemon you are looking for does not exist."
    }
  },
  "notFound": {
    "title": "Page not found",
    "description": "The page you are looking for does not exist."
  }
};
export default messages;